In [1]:
# Import TensorFlow
import tensorflow as tf

# Basic imports
import numpy as np
import pandas as pd

## Define a Constant

In [2]:
# Define a Constant
tensor_constant = tf.constant([[23,4], [32,52]])

In [4]:
tensor_constant

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 52]], dtype=int32)>

In [5]:
# Shape
tensor_constant.shape

TensorShape([2, 2])

## Get values of a Constant

In [7]:
# Getting the values straight from TensorFlow Constant with numpy. Does not show dtype. 
tensor_constant.numpy()

array([[23,  4],
       [32, 52]], dtype=int32)

In [8]:
# Convert numpy array back to a Tensorflow tensor
numpy_tensor = np.array([[23,4], [32,51]])

In [9]:
tensor_from_numpy = tf.constant(numpy_tensor)
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

## Variables

In [10]:
tf_variable = tf.Variable([[1,2,3], [4,5,6]])
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [11]:
# Use numpy to get info
tf_variable.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [12]:
# Use ".assign()" to change a inside variable. ** tf.variable[row,item_in_row] **
tf_variable[0,1].assign(200)
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[  1, 200,   3],
       [  4,   5,   6]], dtype=int32)>

## Operations with Tensors

In [13]:
# Tensor Constant
tensor = tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Addition 

In [14]:
# Add 2
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [15]:
# Add 5
tensor + 5 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 7],
       [8, 9]], dtype=int32)>

In [16]:
# Original still untounched.
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Multiplication 

In [17]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

In [18]:
tensor * 7

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 14],
       [21, 28]], dtype=int32)>

## Using NumPy functions on TensorFlow tensors

In [19]:
# Getting the squares of all numbers  in a TF object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [20]:
# Getting the square root
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

### Dot product between two tensors

In [21]:
tensor_constant

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 52]], dtype=int32)>

In [22]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [23]:
np.dot(tensor, tensor_constant)

array([[ 87, 108],
       [197, 220]], dtype=int32)

## Strings in TensorFlow

In [24]:
tf_string = tf.constant('TensorFlow')
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

### Simple String Operations

In [25]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [26]:
# Unicode/Decode for NLP
tf.strings.unicode_decode(tf_string, 'UTF8')

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

### Storing arrays of Strings

In [27]:
tf_string_array = tf.constant(['TensorFlow', 'Deep Learning', 'AI'])

In [29]:
# Iterating through the TF string array
for string in tf_string_array:
    print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
